### ISSUE TITLE
Tests failing after vscode-textmate update

### ISSUE THREAD

**Issue by mhansen** [mhansen/hledger-vscode#10]
```
  17) Hledger test case files. build($name.in.hledger)=$name.want Tags.in.hledger:
     TypeError: Cannot read property 'theme' of undefined
      at new e (node_modules/vscode-textmate/release/webpack:/vscodetextmate/out/main.js:52:14)
      at Object.build [as default] (tests/build.js:5:20)
      at Context.<anonymous> (tests/test.ts:13:22)
      at processImmediate (internal/timers.js:458:21)
```

**Comment by mhansen** [comment]
Tests are passing now
